/// Dual-Engine TUI - 直接启动 OpenCode 原生 TUI，跳过初始化
/// 
/// det 现在直接启动 OpenCode TUI，自动创建配置文件，跳过初始化提示
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    // 获取当前工作目录
    let cwd = env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    
    // 检查是否存在 OpenCode.md
    let opencode_md = cwd.join("OpenCode.md");
    
    if !opencode_md.exists() {
        // 自动创建默认的 OpenCode.md
        let default_config = r#"# OpenCode Project Configuration

This file contains information about your codebase to help the AI agents.

## Project Overview
- **Type**: General Project
- **Language**: Mixed

## Build Commands
- Build: `cargo build`
- Test: `cargo test`
- Run: `cargo run`

## Important Files
- `Cargo.toml` - Rust workspace configuration
- `README.md` - Project documentation

## Notes
- This file was auto-generated by Dual-Engine TUI
"#;
        
        match fs::write(&opencode_md, default_config) {
            Ok(_) => println!("✅ Created OpenCode.md"),
            Err(e) => eprintln!("⚠️  Failed to create OpenCode.md: {}", e),
        }
    }
    
    // 在当前目录的 .opencode/init 创建文件，跳过初始化对话框
    let opencode_dir = cwd.join(".opencode");
    let init_file = opencode_dir.join("init");
    
    if !init_file.exists() {
        if let Err(e) = fs::create_dir_all(&opencode_dir) {
            eprintln!("⚠️  Failed to create .opencode directory: {}", e);
        } else if let Err(e) = fs::write(&init_file, "") {
            eprintln!("⚠️  Failed to create init file: {}", e);
        } else {
            println!("✅ Created .opencode/init (skipping init dialog)");
        }
    }
    
    // 获取环境变量
    let moonshot_key = env::var("MOONSHOT_API_KEY").unwrap_or_default();
    let dashscope_key = env::var("DASHSCOPE_API_KEY").unwrap_or_default();
    let local_endpoint = env::var("LOCAL_ENDPOINT")
        .unwrap_or_else(|_| "https://api.moonshot.cn/v1".to_string());

    // 获取 opencode.exe 路径
    let exe_path = env::current_exe()
        .unwrap_or_else(|_| std::path::PathBuf::from("."))
        .parent()
        .unwrap_or_else(|| std::path::Path::new("."))
        .join("opencode.exe");

    // 启动 OpenCode TUI
    let status = Command::new(&exe_path)
        .env("MOONSHOT_API_KEY", &moonshot_key)
        .env("DASHSCOPE_API_KEY", &dashscope_key)
        .env("LOCAL_ENDPOINT", &local_endpoint)
        .status();

    match status {
        Ok(s) => {
            std::process::exit(s.code().unwrap_or(1));
        }
        Err(e) => {
            eprintln!("❌ 无法启动 OpenCode TUI: {}", e);
            eprintln!();
            eprintln!("💡 提示:");
            eprintln!("  1. 确保 opencode.exe 在 det.exe 同一目录下");
            eprintln!("  2. 或者直接使用：opencode");
            std::process::exit(1);
        }
    }
}